name: flutter_starter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.0
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.2.0
  get_it: ^7.2.0
  go_router: ^4.2.7
  hive: ^2.2.3
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  stream_transform: ^2.0.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/bitmap/
    - assets/images/flags/
    - assets/.env